### ISSUE TITLE
investigate overriding the default cache invalidation

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dev_compiler#121]
As we start tracking summaries in DDC's server, it will make sense to override the default cache invalidation in analyzer. Otherwise we'll end up doing more work than we need to.

For example: `a` imports `b`, which imports `c`, which imports `d`. Suppose the user adds a comment to `d` and then modifies `a`. We should just try to recompile `d` and `a`. Today we recompile all files because we don't have summaries. Once we do, we should be able to avoid recompiling `c` and `b` by stopping the build propagation (see [dev.dart#L112][1]). For that to work, we also need to override the analyzer's cache invalidation. Otherwise, when we recompile `a`, the analyzer will think it needs to recompute `b` and `c` as well.

[1]: https://github.com/dart-lang/dev_compiler/blob/04b0b834717f911d6e28dbdc9d841400ead0b87a/lib/devc.dart#L112

**Comment by bwilkerson** [comment]
> ... override the default cache invalidation in analyzer ...

We might already be thinking the same thing, but just to be sure...

First, we should replace the current cache management in analyzer, not provide a way to override it. There isn't any reason for analyzer to have a different caching scheme than DDC (or anything else) so there should be only one implementation.

Second, this work should be done in the context of the new task model so that we minimize the amount of duplicated effort.

**Comment by sigmundch** [comment]
> First, we should replace the current cache management in analyzer, not provide a way to override it.  There isn't any reason for analyzer to have a different caching scheme than DDC (or anything else) so there should be only one implementation.

Good question.  Recently talking with @leafpetersen about this, we thought there might be reasons where DDC's caching could be different than the analyzer's. For example, changes in information that the analyzer does not track but we do (like inferred types), or changes that could affect codegen, but not analysis results.

I'm not sure if all these differences always mean that DDC invalidates more than the analyzer would, though. This will hopefully become clearer as we start building and using summaries.

**Comment by bwilkerson** [comment]
> ... we thought there might be reasons where DDC's caching could be different than the analyzer's.

I'd like to proceed on the assumption that they won't be different until proven wrong.

> ... inferred types ...

I still think that there's a good chance that we should replace the analyzer's current implementation of propagated types with the inferred types from DDC. I think it will lead to a better UX because (a) the DDC type system is better thought out than what we did and (b) doing so would mean that the two couldn't provide conflicting information.

**Comment by jmesserly** [comment]
> I'd like to proceed on the assumption that they won't be different until proven wrong.

+1 to that :)

**Comment by jmesserly** [comment]
I suspect this will all be sorted out once we have summaries, which we're tracking as Q3 task. Closing for now.
