### ISSUE TITLE
Limit inference to publicly visible types

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#127]
We currently infer the most precise type we can, even when that type would not be normal visible.  For example, in the following, we'd give no errors or warnings since we infer localfoo as a _FooImpl.

Should we restrict the inferred type?  (E.g., localfoo as Foo?)  If so, should we only restrict private types or also public ones that are not visible?  (E.g., imagine _FooImpl was a public type FooImpl in a separate library not directly imported by main.dart.)

main.dart:
```dart
import 'foo.dart';

void main() {
  final localfoo = myfoo;
  localfoo.x = 42; // Static error or warning?
  print(localfoo.y); // Ditto?
}
```

foo.dart:
```dart
abstract class Foo {
  int get x;
}

var myfoo = new _FooImpl();

class _FooImpl implements Foo {
  int x;
  String y = "hello";
}
```

@leafpetersen @sigmundch

**Comment by sigmundch** [comment]
It's an interesting question. My currently inclination is to say no. That is, we should not limit inference to public interfaces only.

There is precision in knowing the private types, however, we do need to be careful about whether or not we can refer to the type in codegen (e.g. to inject a cast)

At a minimum, I'd like to include private types in inferring the type for `myfoo` in the example above. I view this as being equivalent to how Dart doesn't require that you only use private types in public APIs either. So we would infer the right types if the user wrote this:

```dart
abstract class Foo {
  int get x;
}

_FooImpl myfoo = new _FooImpl();

class _FooImpl implements Foo {
  int x;
  String y = "hello";
}
```

In other words, if you used this `main.dart`:
```dart
import 'foo.dart';

void main() {
  myfoo.x = 42;   // no error if using _FooImpl
  print(myfoo.y); // no error if using _FooImpl
  print(myfoo.z); // error always
}
```

If you put `Foo` as the type of `myfoo`, all 3 lines will show a warning when you run `dartanalyzer main.dart`, but if you type `_FooImpl` as the type of `myfoo`, you only get the third line as an error. I'd like inference to behave like writing `_FooImpl` in this case.

True, the local inference of `localfoo` is slightly different, but I think of it similarly. I would avoid adding more errors/warnings in cases where we know it is safe to use certain API.

**Comment by jmesserly** [comment]
> There is precision in knowing the private types, however, we do need to be careful about whether or not we can refer to the type in codegen (e.g. to inject a cast)

Yeah, we can't. One would hope that, since the type was inferred, no check is needed.

> Should we restrict the inferred type? [...] If so, should we only restrict private types or also public ones that are not visible? [...]

Not sure how I feel about the overall question. At least `var _myfoo = new _FooImpl();` should be _FooImpl. If `myfoo` is public it's a more tricky to say the right behavior. Mixing private and public like that in an API feels odd. Our API documentation tools don't (or didn't) handle this case very well. Should autocompletion suggest the setter or any public members on _FooImpl as possibilities? Suddenly all of those _FooImpl members become part of the public API and subject to breaking changes. Granted, `dynamic` already did that, but now it's the type system exposing those members. Then again, maybe we have this problem already, as Siggi notes in the `_FooImpl myfoo` example. What do tools do now?

Also, if we did want to conclude "Foo", how could we? In that example it works... but you could have `class _FooImpl implements Foo, Bar, Baz` ... then what? :)

**Comment by sigmundch** [comment]
> One would hope that, since the type was inferred, no check is needed.

Here is an example that could be problematic:

```dart
import 'foo.dart';

class Foo2 implements Foo { ... }
Foo methodReturningFoo2() => new Foo2();

main() {
  var localfoo = myfoo; // inferred as _FooImpl;
  if (...) {
    localfoo = new Foo2(); // produces static-type-error
  } else {
    localfoo = methodReturningFoo2(); // tries to inject a _FooImpl cast?
  }
}
```

Here are some viable options I see:
* **option a**:  infer `localfoo` as `_FooImpl`, but make it a compile-time error if we are in a situation where a cast is needed (then users will need to write the type explicitly)

* **option b**: keep `localfoo` as `dynamic`. 

* **option c**: do not limit inference to the initializer, but also look at other assignments on local vars and find the LUB.

I'm currently debating between **a** and **b**. I think option **c**  complicates inference by a lot, so I don't believe it is worth it. While option **b** is the simplest, but it would be interesting to measure how it affects our metrics.

We should also consider how we plan to integrate with the analyzer in the future. In particular, our inferred types and the analyzer propagated types are closely related. We have talked about making both one and the same, for example. If we think of it that way, then it's good to think what is better for hints and code-completion purposes. For example, I think options *a* and *c* are better in that case.

**Comment by vsmenon** [comment]
@jmesserly raises a good related, but somewhat orthogonal-to-inference point.

foo.dart:
```dart
_FooImpl myfoo;
```

main.dart:
```dart
import 'foo.dart';

dynamic foo1 = ...;

void main() {
  myfoo = foo1; // We insert an implicit cast to _FooImpl here.
}
```

Currently, we cannot refer to _FooImpl in main in the generated code (I think).  So, we'd break on this.

@sigmundch Some more options:

- option d: Make it a static error if a library has a public api that contains a private type.
- option e: 'Promote' types in public apis to public / visible ones.  This isn't really possible though if a parameter type is private.
- option f: Expose escaping private types in JS and carry one.

**Comment by jmesserly** [comment]
> Currently, we cannot refer to _FooImpl in main in the generated code (I think). So, we'd break on this.

yeah. I guess it's not really hard to fix, just need to export the private type names too. Just seems a bit odd, since an actually-private pattern is more natural than ES6. it's sort of strange to need to an implicit check for something you couldn't have written explicitly. Not a big deal though.

**Comment by sigmundch** [comment]
And to add another option that came up in our discussions:
 * **option g**: expose publicly a function to perform instance of checks/casts:

foo.dart:
```dart
_FooImpl castAs_FooImpl(x) => x as _FooImpl;
```

so you can do this in main.dart:
```dart
import 'foo.dart';
dynamic foo1 = ...;
main() {
   myfoo = castAs_FooImpl(foo1); 
}
```

**Comment by eernstg** [comment]
On Wed, Apr 8, 2015 at 9:23 PM, sigmundch <notifications@github.com> wrote:

> One would hope that, since the type was inferred, no check is needed.
>
> Here is an example that could be problematic:
>
> import 'foo.dart';
> class Foo2 implements Foo { ... }
> Foo methodReturningFoo2() => new Foo2();
>
> main() {
>   var localfoo = myfoo; // inferred as _FooImpl;
>   if (...) {
>     localfoo = new Foo2(); // produces static-type-error
>   } else {
>     localfoo = methodReturningFoo2(); // tries to inject a _FooImpl cast?
>   }
> }
>
> Here are some viable options I see:
>
>    -
>
>    *option a*: infer localfoo as _FooImpl, but make it a compile-time
>    error if we are in a situation where a cast is needed (then users will need
>    to write the type explicitly)
>    -
>
>    *option b*: keep localfoo as dynamic.
>    -
>
>    *option c*: do not limit inference to the initializer, but also look
>    at other assignments on local vars and find the LUB.
>
> I'm currently debating between *a* and *b*. I think option *c*
> complicates inference by a lot, so I don't believe it is worth it. While
> option *b* is the simplest, but it would be interesting to measure how it
> affects our metrics.
>

Hello all,

this is an old, but important discussion.  I can't help restating my
position:  Did you consider

    - using a quickfix inserting the inferred type (better: offering a
choice among a few possible inferred types), such that the programmer gets
to take the responsibility for the choice, and such that the actual code
documents this choice?

    - inferring a type, no matter whether it's used in a quickfix or as an
inferred type, based on the complete set of usages of `localfoo` in its
scope, not just its init-expression?  To me, "tries to inject a .. cast"
looks like a wrong decision based on another wrong decision (I guess that's
why you added the '?' and described this situation as problematic in the
first place), but a scope-global analysis would also have produced the type
`Foo` rather than `_FooImpl` in the first place.

By the way, I think the chosen type (here: for a local variable, but also
for other type annotations) documents the desired point of view on the
declared entity.  During construction of a complex object we may wish to
know every detail about its parts (so we can build a `new
_ThingyImpl(part1, part2, ...)` using private types galore for `part...`),
but otherwise the

    most _general_ type G that will allow us to perform the task at hand

will probably be the most comprehensible and maintainable choice.  In
contrast, inference would prefer the most _specific_ type S that is
justified by incoming values (for a variable: a init expression plus all
assignments), and that would again support the greatest possible set of
_usages_ of the value of that variable, but it would constrain the
_assignments_ (added during an editing session, after the inference has
taken place) to that variable to stay within the arbitrary,
invisibly-inferred golden cage of S.  This is exactly what happens when
`methodReturningFoo2() as _FooImpl` fails at runtime.

  best regards,

-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by leafpetersen** [comment]
A couple of comments:

First, my immediate instinct is that forbidding private types in public APIs is probably too restrictive, simply because Dart is not very good about allowing the programmer to specify what is part of the public API and what isn't.  But I could be wrong - maybe we should try to get some data on this?

Second, for good or for ill, Dart library privacy is only designed to prevent you from naming library private things, not from using them, and I personally feel that trying to add use enforcement after the fact is just making things inconsistent.  Consider:

```dart
// a.dart
class _Foo {
  int x;
}
_Foo gimmeAFoo() => new _Foo();

// b.dart
import 'a.dart';
void main() {
   var a = gimmeAFoo();
   a.x = 3;  // Stmt 1
   gimmeAFoo().x = 3;  // Stmt 2
}
```

Statement 2 is statically and dynamically allowed in Dart (DDC flavored or regular), with or without inference, since the type of a call to gimmeAFoo() is a type which has an integer x field.  

Statement 1 is allowed in Dart (DDC flavored or regular) without inference (since a is dynamic).

Our question is, should Statement 1 be allowed in Dart with inference?  My sense is that saying no is surprising for two reasons.  First, there's a sense in which inference should be making things better, either by turning a dynamic error into a static error, or by eliminating an unnecessary static or dynamic error: in this case it's doing neither.  Secondly, there's a sort of substitution/abstraction principle that it would be nice to adhere to as much as possible: binding an expression to a variable (or replacing a variable with its definition) should as much as possible not change the well-typedness of the program.  With our restricted forms of inference we obviously fall down on the latter in places (e.g. binding a closure expression to a variable stops contextual inference from working on it), but nonetheless I think as a design goal it provides good general guidance and in this case argues for just inferring the private type.

The main argument in favor of disallowing this is to enforce a sort of abstraction property via library privacy.  This is fair enough, but as the example shows it really has nothing directly to do with inference: if we really want to enforce this, then we should probably consider disallowing Statement 2 in the example above as well, since it violates exactly the same abstraction property in exactly the same way.

**Comment by jmesserly** [comment]
yeah, @leafpetersen I agree. The only thing that weirds me out is introducing implicit checks that couldn't have been written explicitly. No reason we can't implement it that way, though

**Comment by jmesserly** [comment]
(but I'm probably biased, I'm not a fan of implicit checks anyway)

**Comment by eernstg** [comment]
Why not require that a declared name has a type whose scope includes the
scope of the name itself?  That is, `_Foo _gimmeAFoo(_Bar bar)` is fine,
because the scope of _gimmeAFoo is the library, which is included in
(actually equal to) the scope of `_Foo` and `_Bar`, but `_Foo
gimmeAFoo(_Bar bar)` is violates this rule because `gimmeAFoo` can be seen
from other libraries, where `_Foo` and `_Bar` are out of scope.  When no
declared names have a type whose scope is smaller than the name itself then
this issue does not arise.  A version of _gimmeAFoo that is appropriate for
public access could be written as a wrapper, with suitable public types.
If _Foo <: Foo and _Bar <: Bar then returning a _Foo would be
unproblematic, and accepting a Bar would give rise to the usual covariance
related checks, if it is actually really necessary for _gimmeAFoo to insist
on receiving a _Bar, in which case there may be a need for some
checking/glue code, anyway.


On Sat, Apr 11, 2015 at 12:06 AM, John Messerly <notifications@github.com>
wrote:

> (but I'm probably biased, I'm not a fan of implicit checks anyway)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dev_compiler/issues/127#issuecomment-91705136>
> .
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by leafpetersen** [comment]
@eernstg - That's basically the option of forbidding private types in public APIs that I mentioned in my first bullet[1].  I'm certainly open to seeing experiments along this line to see how much existing code we would break.  My suspicion is that there will be a fair bit of code which is not sufficiently hygienic about using private names for private symbols to satisfy this restriction though, and it's not clear to me that we really need to be looking for yet more reasons to reject code that full Dart accepts.  This probably would be a fairly easy data collection experiment for somebody to do at some point though, in all of our copious spare time... :)


[1] Actually, I think your phrasing is much more restrictive, since it would presumably also disallow:

```
import 'foo.dart' show Foo;

Foo gimmeAFoo()
```

since any import of gimmeAFoo violates the scope restriction (unless foo.dart happens to be imported along with it).

**Comment by eernstg** [comment]
On Mon, Apr 13, 2015 at 9:47 PM, Leaf Petersen <notifications@github.com>
wrote:

> @eernstg <https://github.com/eernstg> - That's basically the option of
> forbidding private types in public APIs that I mentioned in my first
> bullet[1]. I'm certainly open to seeing experiments along this line to see
> how much existing code we would break. My suspicion is that there will be a
> fair bit of code which is not sufficiently hygienic about using private
> names for private symbols to satisfy this restriction though, and it's not
> clear to me that we really need to be looking for yet more reasons to
> reject code that full Dart accepts.
>
Thinking about it again, your version is both simpler and probably more
practical --- "no private types in public APIs" is easy to remember.

However, if that does turn out to be too restrictive, it might be
worthwhile to retrace the underlying motivation for privacy in the first
place:  Dart privacy is probably not safe as the foundation of any kind of
security policies, but it is capable of helping programmers avoid relying
on certain parts of a software system (let's call them implementation
details). Excessive dependencies involving implementation details may be
convenient at a microscopic scale, but obviously it's quite costly at a
more global scale.

If we want to maintain this "protect me from implementation details"
feature, it would be more helpful to programmers to keep the private types
private, rather than setting up the tool support and everything else to
aggressively exploit private types. Because of this, I'm not very happy
about directly using the interface of _Foo on the result returned from
gimmeAFoo() in some other library than the one that defines _Foo.

However, a type playing a role like _Foo would often have some public
supertypes that you can depend on without ill effects on the architecture.
One possible approach could be to "raise" each private type in an imported
composite type (such as a method signature) to the least public supertype.
So, when _Foo implements/extends Foo we'll consider the invocation
gimmeAFoo() to have type Foo when outside the library that defines _Foo.

(OK, the 'least public supertype' would in general be an intersection type,
so there might be some technicalities; and OK, this works well for types in
covariant positions like function/method return types, but for types in
contravariant positions like argument types we would have to rely on the
downcasting side of assignability; then again incoming values, such as
arguments, should probably gravitate toward public types anyway, certainly
for functions/methods that are intended to be used in other libraries; etc.)

> This probably would be a fairly easy data collection experiment for
> somebody to do at some point though, in all of our copious spare time... :)
>
> [1] Actually, I think your phrasing is much more restrictive, since it
> would presumably also disallow:
>
> import 'foo.dart' show Foo;
>
> Foo gimmeAFoo()
>
> since any import of gimmeAFoo violates the scope restriction (unless
> foo.dart happens to be imported along with it).
>
Good point! However, privacy seems to be slightly tricky in Dart:  ECMA-408
p105 has this:

  'Libraries are units of privacy. A private declaration declared within a
library
L can only be accessed by code within L. Any attempt to access a private
member declaration from outside L will cause a method, getter or setter
lookup
failure.'

.. but presumably it does not count as 'access' to the declaration _Foo
when we use a member which is declared in _Foo (and nowhere else):

-------------------------------------------------------------------
// File 'main.dart'.

import 'b.dart';

main() {
  int x = returnPublic().publicInPublic;
  int y = returnPrivate().publicInPrivate;
}

-------------------------------------------------------------------
// File 'b.dart'.

import 'c.dart';

class _Foo extends Foo {
  int publicInPrivate;
  int _privateInPrivate;
}

Foo returnPublic() => new Foo();
_Foo returnPrivate() => new _Foo();
-------------------------------------------------------------------
// File 'c.dart'.

class Foo {
  int publicInPublic;
}
-------------------------------------------------------------------

Sure, we can't use `_privateInPrivate` in main.dart, and we can't declare a
variable of type `Foo` and initialize it to a `new Foo()` (for instance, we
get "Undefined class 'Foo'" from the analyzer and "type 'Foo' not loaded"
at runtime from the vm), but we _can_ initialize `x` and `y` as shown
above. This means that the features of `Foo` are made available even though
that class has not been imported into main.dart, and the features of `_Foo`
are made available even though that class is private and not defined in
main.dart.

Where does ECMA-408 and its newer brethren say so? I can't spot it right
now, anyway. ;-)

Maybe the rule is that we will recursively "auto-import" all name spaces
arising via composite expressions (here: we auto-import c.dart into
main.dart to get the Foo class body name space because of the `.` in
`returnPublic().publicInPublic`), but it's not obvious how you'd justify
the access to `publicInPrivate`.  It's a "friendly" choice, but it does
allow for unlimited dependencies on "implementation details" anywhere in a
program.  Is that really what we want?

  best regards,

-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by jmesserly** [comment]
@vsmenon -- should we close this? I think we're leaning towards not changing anything?

**Comment by jmesserly** [comment]
Closing this out. Code has moved to Analyzer in any case :)
