### ISSUE TITLE
cache folder hard to navigate in devtools sources view

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#140]
The "sources" view in devtools is a bit hard to navigate in server mode:

> localhost:8080
>> cached
>>> *long hash code*/dev_compiler/runtime/dart
>>> *long hash code*/...
>>> *long hash code*/...
>>> *long hash code*/...
>>>> collection.js

>>> *long hash code*
>>>> sunflower.js

it's hard to predict where my file will be.

Do we actually need to store a folder with the hash code on disk? Presumably the server can just compute that on demand, and encode relevant hash in the cache headers, or cache busting query string? That would make the sources view a lot more navigable.

**Comment by sigmundch** [comment]
Note that hash portion of the URL is added by the server. On the temporary folder on disk we don't include these hashes altogether.

Let me give some context of how we ended up with this design. Currently we use `shelf` and `shelf_static` to implement the server. Out of the box `shelf` supports delegating requests to other handlers and "consuming" a few segments at the beginning of the URL before you pass a request to another handler. The `shelf_static` package has the logic to serve files with mimetypes directly from disk. The current implementation takes off the hash from the URL, loads the file using `shelf_static`, and if the hash was present, it attaches a caching policy to the HTTP response.

I actually also tried to put the hash as a suffix of the file-name, like `file/to/file.longhash.js`. But I didn't go with it because I wasn't happy with the alternatives I had to pick from. In particular:

1. rename the URL before delegating to `shelf-static`: my understanding was that this was too hacky. In particular, `shelf` doesn't want you to modify the URL as you delegate to another handler.
1. emit hashes on disk: I didn't try this, but it should be possible, then `shelf_static` would work out of the box.
1. fork the `shelf_static` package to handle hashes: this way we could the hash from the filename at the last moment when we are about to find it on disk.

Thinking more about it option 2 is not necessarily that bad (I'm not sure why I didn't like it at the time though).

**Comment by jmesserly** [comment]
Ah, right, the folder on disk is currently different, forgot about that. In an ideal world, we'd use the same structure so features like https://developer.chrome.com/devtools/docs/workspaces will work for resource files. (we also need to not copy files though.)

I'd probably lean towards option 3. It sounds like shelf-static is not letting us get the caching behavior we want in a development server. But option 2 sounds like an easy step in the right direction.

**Comment by vsmenon** [comment]
For now, I've got a CL to just disable hashing by flag (--no-hashing):

https://codereview.chromium.org/1088703003/

It'd still be on by default.

**Comment by vsmenon** [comment]
The above is landed.  For now, use:

dartdevc --server --no-hashing index.html

to avoid this issue.

**Comment by sigmundch** [comment]
For some reason I thought the query parameter was not going to work, but it seems to work now that I checked it. Here is a CL to fix it:

https://codereview.chromium.org/1131933003

Now the source view is more like:
```
  dev_compiler/runtime/dart
     collection.js?____cached=209134821234
     async.js?____cached=4122091234823
  sunflower.js?___cached=120912348234
```

I added the extra `____` to make the filename stand out in the inspector
