### ISSUE TITLE
implement dart:js for ddc

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#168]
Angular uses this statically, although the hello world sample does not hit it.

@jacob314

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1179643005/ adds code to the build, we need to go through it and make sure it actually works though :)

**Comment by jmesserly** [comment]
it looks like we have almost no dart:js tests in the Dart SDK(!) ... going to write some tests, and also review the code we pulled in ...

**Comment by jacob314** [comment]
There are about 1000 lines of tests for dart:js in the sdk:
tests/html/js_test.dart

**Comment by jmesserly** [comment]
oh, nice! I kind of assumed that was mostly the dart:html integration side, but yeah, it looks like some bits in that can be stolen, like the JsArray tests. Nice!

**Comment by jacob314** [comment]
Yeah those tests barely have to do with dart:html integration. They are in
that directory mainly because we never bothered to create a separate
directory.

**Comment by jmesserly** [comment]
update: I'm getting closer to having the code+tests working. amusingly, hitting problems just getting package:test to work (e.g. #226 and #227) ... once that's clear I'll see how the tests are doing.

The strange thing: for now, we'll continue to proxy generic Dart and JS objects when crossing the boundary, including Arrays, even though that's totally useless to do in DDC (especially for Array). That should give API compatibility with existing apps, though. Otherwise, you'd never be able to get a JsObject/JsArray instances.

An alternative design would be to make all JS objects and Arrays "pretend" to have JsObject implemented. We could support calling those members on all objects. Looking over the interface:
```dart
class JsObject {
  callMethod(method, [List args]);
  void deleteProperty(property);
  bool hasProperty(property);
  bool instanceof(JsFunction type);
  void operator[](property);
  void operator[]=(property, value);
}
```

It wouldn't be too bad to just have those methods on there. Naturally, you'd get a static error trying to call them, unless the target type is `dynamic` or `JsObject`. @jacob314 is that along the lines of what you were thinking for the existing dart:js package?

**Comment by jacob314** [comment]
That is what I was thinking. Having those extension methods on all JS
objects is a little annoying but i think is something we could live with if
need be and would give a better compatibility story with existing code.

**Comment by jmesserly** [comment]
also just fixed #231 ... still fixing out unrelated issues to see if I can get my tests passing.
Leaning towards a two-step approach here:
- [ ] implement dart:js that is fully compatible with existing one
- [ ] implement dart:js that passes arrays/JS objects transparently, but still supports the JsObject interface on them via dynamic invoke

Ideally we can do the second step at the same time that dart2js and dartium do, so we aren't losing compatibility those implementations.

**Comment by jmesserly** [comment]
this is proving harder than I thought ... had to make my own lightweight test functions since we can't run package:test yet. I'm down to a handful of test failures though.

**Comment by jmesserly** [comment]
finally ... https://codereview.chromium.org/1200233004/
