### ISSUE TITLE
The dynamic identifier needs to be mapped to dart.dynamic 

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#184]
We handle 'dynamic' correctly when it appears as a type literal, but not when it appears as an identifier.  E.g., the dynamic in the print below triggers an error:

void main() {
  dynamic x = 42;
  print(x == dynamic);
}

**Comment by jmesserly** [comment]
yeah, what's happening is visitSimpleIdentifier has no special handling for types.
I wonder if it should send all types to _emitTypeName?

I suppose it doesn't really matter since other type literals are generated correctly... but might be safer to have _emitTypeName be the only place that emits types.

**Comment by jmesserly** [comment]
found another broken case: returning `Generic` from inside `class Generic<T>` ... this binds to the `Generic<T>` name instead of `Generic<dynamic>`. That makes me think _emitTypeName is the place to send this.
