### ISSUE TITLE
JSNumber methods not invoked correctly

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#216]
The following triggers a runtime error in ddc:

```dart
main() {
  print(4.isEven);
}
```

Generates: Uncaught TypeError: this[dartx.&] is not a function

It appears the `&` operator is not explicitly defined in JSInt - perhaps dart2js is just falling back on the underlying one?

**Comment by vsmenon** [comment]
Adding this to JSInt:
```
  int operator &(int i) => JS('JSUInt32', '# & #', this, i);
```

fixes the above error.  @jmesserly : Should we do this explicitly?  Implicitly in the compiler?

**Comment by jmesserly** [comment]
Hmmm. I see `num operator &(num other)` on JSNumber. Does anything on JSNumber work? Maybe we're failing to walk up the prototype chain when we examine the members of JSInt. That's my guess. I vaguely remember noticing this before, but apparently forgot to fix it somehow :)

Easy fix would be to move JSInt methods to JSNumber and switch which type is the extension. Not sure if there's something smarter we can do. Walking the proto is a bit tricky, because we'd need to stop at core.Object. Probably fine too though.

**Comment by vsmenon** [comment]
Yes - that looks right.  I'm hitting errors on other JSNumber methods as well.

**Comment by vsmenon** [comment]
BTW, do we still have a need for JSDouble and other types in that file?  Perhaps merging makes sense.

In general, do we want to allow classes annotated JsPeerInterface to be able to inherit from classes that are not?  We need special handling for those supertypes, right?  E.g., Pattern for String.

**Comment by jmesserly** [comment]
yeah, good questions, I was wondering those too: https://codereview.chromium.org/1173903003/
Merging totally makes sense, I think. Should I pull the trigger? I could revert the changes in dart_runtime.js

Note the other bug fix though. Pretty sure we want that one regardless. It makes sure `dartx` symbols are declared before use.
