### ISSUE TITLE
Handle await/async in the type checker

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dev_compiler#264]
Using `dartanalyzer --strong lib/test.dart` from `Dart VM version: 1.12.0-dev.4.0 (Tue Jul 21 03:40:25 2015) on "macos_x64"`

`liveTests` is a `List` below. While it doesn't return a `Future<bool>` directly, it is in an async block.

```dart
  Future<bool> get success async {
    await _group.future;
    if (_closedBeforeDone) return null;
    return liveTests.every((liveTest) =>
        liveTest.state.result == Result.success);
  }
```

Error

```
[error] Type check failed: liveTests.every((liveTest) => liveTest.state.result == Result.success) (bool) is not of type Future<bool> (/Users/kevmoo/source/github/test.dart/lib/src/runner/engine.dart, line 81, col 12)
```

**Comment by kevmoo** [comment]
Similar

```
[error] Type check failed: await suite; (Suite) is not of type Future<Suite> (/Users/kevmoo/source/github/test.dart/lib/src/runner/load_suite.dart, line 132, col 41)
```

```dart
  Future<Suite> getSuite() async {
    var liveTest = await tests.single.load(this);
    liveTest.onPrint.listen(print);
    await liveTest.run();

    if (liveTest.errors.isEmpty) return await suite;

    var error = liveTest.errors.first;
    await new Future.error(error.error, error.stackTrace);
    throw 'unreachable';
  }
```

**Comment by jmesserly** [comment]
I already have a fix for this.

**Comment by kevmoo** [comment]
Can we keep this open to track getting the SDK release updated w/ the fix?

**Comment by jmesserly** [comment]
these only track open bugs w.r.t. master branch.
the fix isn't landed yet, though. Hence why this is still open :)
I'm happy to push it into SDK, after it's checked in here.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1248213002/

**Comment by jmesserly** [comment]
oh, hmm. My CL might only fix half of this (return await). I'll see about the rest.

**Comment by jmesserly** [comment]
ah, I think the rest is fixed by pulling in Vijay's previous support.

**Comment by jmesserly** [comment]
should be fixed now (and in sdk too!)

**Comment by vsmenon** [comment]
On Wed, Jul 22, 2015 at 3:50 PM, Kevin Moore <notifications@github.com>
wrote:

> Similar
>
> [error] Type check failed: await suite; (Suite) is not of type Future<Suite> (/Users/kevmoo/source/github/test.dart/lib/src/runner/load_suite.dart, line 132, col 41)
>
>   Future<Suite> getSuite() async {
>     var liveTest = await tests.single.load(this);
>     liveTest.onPrint.listen(print);
>     await liveTest.run();
>
>     if (liveTest.errors.isEmpty) return await suite;
>
>
Why isn't the answer here to just return 'suite' instead of 'await suite'?
Isn't the await unnecessary?

**Comment by jmesserly** [comment]
I think `return` is used to complete the future, so both would work (because of futures flattening). Quick test on the VM confirms this.

In the spec, it's split between Function Invocation (16.14):
> If f is marked async (9), then a fresh instance (10.6.1) o implementing the
built-in class Future is associated with the invocation and immediately returned
to the caller. The body of f is scheduled for execution at some future time. The
future o will complete when f terminates. The value used to complete o is the
Dart Programming Language Specification 70
current return value (17.12), if it is defined, and the current exception (16.9)
otherwise.

And Return (17.12):
> Let T be the static type of e and let f be the immediately enclosing function.
It is a static type warning if the body of f is marked async and the type
`Future<flatten(T)>` (16.10) may not be assigned to the declared return type of
f. Otherwise, it is a static type warning if T may not be assigned to the declared
return type of f.
Let S be the runtime type of o. In checked mode:
• If the body of f is marked async (9) it is a dynamic type error if o is
not null (16.2) and `Future<S>` is not a subtype of the actual return type
(19.8.1) of f.
• Otherwise, it is a dynamic type error if o is not null and the runtime type
of o is not a subtype of the actual return type of f.

**Comment by jmesserly** [comment]
Oops, we don't allow returning a Future, due to the flattening issue. Should we reopen?
It's this issue: https://github.com/dart-lang/dev_compiler/issues/228
