### ISSUE TITLE
Test framework not always reporting errors

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#292]
Looking at the console on a `karma start`, I see a few errors like the below even though all tests appear to pass.  Is there an error not getting properly reported?

```
:9876/base/lib/runtime/_operations.js?5bb4f1a9f450d332127a49a39b33f1033b58e0d1:283 Uncaught Uncaught Error: Expect.equals(expected: <abcdYefC>, actual: <abcdeffg>) fails.
Stack Trace:
Error
    at Object.throw_ [as throw] (http://localhost:9876/base/lib/runtime/_operations.js?5bb4f1a9f450d332127a49a39b33f1033b58e0d1:281:23)
    at Function._fail (http://localhost:9876/base/test/codegen/expect/expect/expect.js?453ffeb1524b5a0f46cf9d3d1c410416f31906d4:270:17)
    at Function.equals (http://localhost:9876/base/test/codegen/expect/expect/expect.js?453ffeb1524b5a0f46cf9d3d1c410416f31906d4:74:14)
    at Tracer.done (http://localhost:9876/base/test/codegen/expect/language/asyncstar_throw_in_catch_test.js?b2af34ab8ccfd68e24b676ad7917d25abb872740:28:21)
    at http://localhost:9876/base/test/codegen/expect/language/asyncstar_throw_in_catch_test.js?b2af34ab8ccfd68e24b676ad7917d25abb872740:145:16
    at _RootZone.runGuarded (http://localhost:9876/base/lib/runtime/dart/async.js?c4a35dce2288c10052ae7e9726342dd296124b05:5222:18)
    at _ControllerSubscription.<anonymous> (http://localhost:9876/base/lib/runtime/dart/async.js?c4a35dce2288c10052ae7e9726342dd296124b05:1140:23)
    at _ControllerSubscription.asFuture.futureValue (http://localhost:9876/base/lib/runtime/dart/async.js?c4a35dce2288c10052ae7e9726342dd296124b05:1149:11)
    at _DelayedDone.perform (http://localhost:9876/base/lib/runtime/dart/async.js?c4a35dce2288c10052ae7e9726342dd296124b05:3695:26)
    at _StreamImplEvents.handleNext (http://localhost:9876/base/lib/runtime/dart/async.js?c4a35dce2288c10052ae7e9726342dd296124b05:3735:13)
```

@jmesserly ?

**Comment by jmesserly** [comment]
Haven't seen that before.

**Comment by vsmenon** [comment]
@leafpetersen is also seeing this on HEAD.  As best as I can tell, it's only happening on a small number (3) async tests.  The framework is reporting a pass - maybe these exceptions are happening too late?

**Comment by jmesserly** [comment]
> The framework is reporting a pass - maybe these exceptions are happening too late?

Maybe. We aren't calling `done` until the future completes though:

https://github.com/dart-lang/dev_compiler/blob/d862ed1793b495e06f86117661178189319f5fd4/test/codegen/unittest.dart#L24

and if we don't call done, it should record a timeout failure.

I was having no problems getting async failures to cause Karma failures, at least for every test I debugged through Karma...

**Comment by jmesserly** [comment]
Figured it out. Fix incoming.

**Comment by jmesserly** [comment]
(`main` of language tests can return a Future)

**Comment by jmesserly** [comment]
Oh, hmmm. That didn't fix the problem. It might be that the Dart VM waits for pending async stuff to finish (regardless of whether it was returned by main) ... I'll have to dig into _isolate_helper and see if that stuff is exposed so I can have the test framework wait.

**Comment by jmesserly** [comment]
related: https://github.com/dart-lang/dev_compiler/issues/233
the event loop stuff is quite a mess from an interop perspective ... this one is going to take some digging.

@vsmenon @leafpetersen was this blocking you? if so maybe we should skip the failing tests in the short term. regardless, those test failures are probably caused by a different bug than this one.

**Comment by vsmenon** [comment]
No, not a blocker.  I just noticed it while debugging something else.

**Comment by jmesserly** [comment]
So I tried adding variations on:
```dart
while (_isolate_helper._globalState.topEventLoop.runIteration()) {}
```
... to dartLanguageTest after main, so in theory it waits for all pending operations, but that still doesn't catch it. I think because JS generators aren't known to the _isolate_helper system. Basically our async* is implemented as a stream of events from JS, and it doesn't contain hooks to let _isolate_helper's event loop know what's going on.

Not sure there's an easy fix, that doesn't involve fixing #233, but I'll keep looking...

**Comment by jmesserly** [comment]
Ah, we stumbled into a familiar problem area:
> /// This library is used for testing asynchronous tests.
> /// If a test is asynchronous, it needs to notify the testing driver
> /// about this (otherwise tests may get reported as passing [after main()
> /// finished] even if the asynchronous operations fail).

and

> // TODO(kustermann): This is problematic because we rely on a working
> // 'dart:isolate' (i.e. it is in particular problematic with dart2js).
> // It would be nice if we could use a different mechanism for different
> // runtimes.

from [test/codegen/async_helper.dart](https://github.com/dart-lang/dev_compiler/blob/d862ed1793b495e06f86117661178189319f5fd4/test/codegen/async_helper.dart)

So that explains it :)

I may just modify async_helper.dart to not rely on dart:isolate, as the TODO suggests...

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1289673007/
