### ISSUE TITLE
Unintended interactions between strong mode + fatal-warnings 

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#302]
Consider baz.dart:

```dart
void main() {
  Object o = "hello";
  String s = "world";
  s = o;
  print(s);
}
```

The --fatal-warnings flag reports no issues.  The --strong flag reports a warning that the latter assignment to s will do an implicit cast.  Used together, they report an error.

Perhaps we need to push these down to hints by default?

**Comment by jmesserly** [comment]
yeah, generally our error levels are off-by-one compared to what analyzer_cli reports

**Comment by jmesserly** [comment]
the flip side of this issue is, we may want strong mode to increase the level of some analyzer messages (e.g. static warning is a static error in strong mode). We also have the related issue about duplicate messages (static warning+DDC error).

**Comment by bwilkerson** [comment]
> Perhaps we need to push these down to hints by default?

If you were not changing any existing warnings to be errors, would the message about an implicit cast still be a warning? That is, do you consider it to be as serious an issue as other warnings? (Remembering too that the difference between an error and a warning in Dart is not a difference in degree, but a difference in whether the compiler will produce executable code.) If so, then you should leave it and `--fatal-warnings` should turn it into an error. If not, then it should be changed regardless of whether `--fatal-warnings` is enabled.

> We also have the related issue about duplicate messages (static warning+DDC error).

That problem should be solved by the integration work, because then we'll only be generating one or the other.

**Comment by vsmenon** [comment]
> If you were not changing any existing warnings to be errors, would the message about an implicit cast still be a warning?

Not sure.  This is one of those places we've talked about having a knob.

I think a reasonable rule of thumb to start with:

Error: Won't compile with DDC.
Warning: Will compile, but high likelyhood of failure at runtime.
Hint: Everything else.

By that measure, most implicit casts should probably be hints.  

(There are a few more problematic implicit casts - e.g., if we inject an implicit cast from S to T where T <: S in strong mode, but S <: T in regular, that is likely to be problematic.)
