### ISSUE TITLE
Treat S<dynamic> as S<Object>?

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#38]
We've discussed mapping these to the same:
```dart
S<T>                =>   S == S<Object>
S<T extends Base>   =>   S == S<Base>
```

Should we?
@jacob314 @leafpetersen

**Comment by jmesserly** [comment]
I think we decided the distinction of `dynamic` vs `Object` needs to be preserved at runtime, although it will rarely make a difference. (when T is substituted into function parameter type positions, where `dynamic` is treated as bottom instead of top).

@leafpetersen @vsmenon thoughts on this one?
`S<T extends Base>   =>   S == S<Base>`

**Comment by vsmenon** [comment]
@leafpetersen - is this still an open issue?

**Comment by leafpetersen** [comment]
I believe this is still open.

**Comment by jmesserly** [comment]
moved to https://github.com/dart-lang/sdk/issues/25877
