### ISSUE TITLE
Type values may be wrapped on dload

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#381]
The following code prints true on the VM (as it should) but prints false in DDC:

```dart
class A {
  get type => A;
}

void main() {
  dynamic a = new A();
  print(a.type == A);
}
```

We appear to call bind on the `dload` for `a.type` which doesn't preserve identity.

**Comment by jmesserly** [comment]
> We appear to call bind on the dload for a.type which doesn't preserve identity.

```js
  function dload(obj, field) {
    field = _canonicalFieldName(obj, field, [], field);
    if (classes.hasMethod(obj, field)) {
      return classes.bind(obj, field);
    }
    // TODO(vsm): Implement NSM robustly.  An 'in' check breaks on certain
    // types.  hasOwnProperty doesn't chase the proto chain.
    // Also, do we want an NSM on regular JS objects?
    // See: https://github.com/dart-lang/dev_compiler/issues/169
    let result = obj[field];

    // TODO(vsm): Check this more robustly.
    if (typeof result == "function" && !hasOwnProperty.call(obj, field)) {
      // This appears to be a method tearoff.  Bind this.
      return result.bind(obj);
    }
    return result;
  }
```

I'm guessing the bug is in the "Check this more robustly" ? :)

incidentally, yeah, the hasOwnProperty check won't help. It's assuming everything is a method or a field, with no consideration of getters. I think the right way to reflect on this would be to walk up the prototype chain, calling getOwnPropertyDescriptor, and look at the descriptor. That way we can tell if it's a getter or a value property that is a Function (which for us would always be a method--we don't put value properties on the prototype otherwise).

**Comment by vsmenon** [comment]
Hmm, I'm actually not sure why we need to check and do `result.bind` in the first place.  The `classes.hasMethod` check at the beginning seems to cover the cases we need to bind.  In Angular samples, we never actually hit `result.bind`.
