### ISSUE TITLE
Generic method/function calls are emitted qualified

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/dev_compiler#406]
Currently the representation of a generic method/function call uses the instantiated Member for the method/function as the element for the SimpleIdentifier on the call.  The JS code generator uses a table of top level elements in the module loader to record which top level elements have been loaded.  Currently, generic method invocations will not be found in this table, since they are being looked up by the member, rather than by the original element.

If we continue with this representation in the analyzer, we will need to get back to the original element when we look up the element in the loader table.  The example below demonstrates the problem: the call to `min` will be generated as `exports.min`, whereas the call to `max` will be generated as just `max`.

```dart
num/*=T*/ min/*<T extends num>*/(num/*=T*/ a, num/*=T*/ b) {
  return a;
}

num max(num a, num b) {
  return a;
}

class Rectangle<T extends num> {
  factory Rectangle.fromPoints(T x, T y) {
    T left = min(x, y);
    T right = max(x, y);
    return null;
  }
}
```

cc @jmesserly who may be in the process of changing this representation?

**Comment by leafpetersen** [comment]
Checking for ExecutableMember in visitSimpleIdentifier and projecting back to the baseElement blows some things up, but only doing this for FunctionMember seems to be working.  I think this probably covers all of the cases?

**Comment by jmesserly** [comment]
> Checking for ExecutableMember in visitSimpleIdentifier and projecting back to the baseElement blows some things up, but only doing this for FunctionMember seems to be working. I think this probably covers all of the cases?

FunctionMember would cover generic functions. I don't think this can happen with generic methods (instance or static) because we don't try and track them, as they can't appear at the CompilationUnit level.

> cc @jmesserly who may be in the process of changing this representation?

Yeah I have a CL I'm working on. What it does is have MethodInvocation track the element we're invoking (as well as the function type).

So the SimpleIdentifier node points at the original element (`min` with a bound `T`) and function type (here `<T>(T, T) -> T`).

The MethodInvocation node has two new properties, one that points at the FunctionMember (`min` with `{T_from_Rectangle/T}` in this case), and the other points at an instantiated function type (here `{T_from_Rectangle/T}(T, T) -> T`).

The result of the change is you can easily get to the original element or the instantiated one. It's your choice depending on what you're trying to use it for.

**Comment by leafpetersen** [comment]
This is basically fixed in the roll CL I sent out.
