### ISSUE TITLE
issue dispatching Atom command events

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dev_compiler#414]
```
Uncaught NoSuchMethodError : method not found: 'call'
Receiver: null
Arguments: [Instance of 'JSObject<CustomEvent>']
throw_ @ web/ddc/dev_compiler/runtime/dart/_operations.js:310
throwNoSuchMethod @ web/ddc/dev_compiler/runtime/dart/_errors.js:19
throwNoSuchMethod @ web/ddc/dev_compiler/runtime/dart/_operations.js:102
checkAndCall @ web/ddc/dev_compiler/runtime/dart/_operations.js:114
dcall @ web/ddc/dev_compiler/runtime/dart/_operations.js:141
_convertToDart @ web/ddc/dev_compiler/runtime/dart/js.js:349
wrapper @ web/ddc/dev_compiler/runtime/dart/js.js:339
module.exports.CommandRegistry.handleCommandEvent @ /src/command-registry.js:260
__bind @ /src/command-registry.js:3
module.exports.CommandRegistry.dispatch @ /src/command-registry.js:160
module.exports.AtomEnvironment.dispatchApplicationMenuCommand @ /src/atom-environment.js:1013
emitOne @ events.js:77emit @ events.js:169
```

I see an exception when Atom tries to dispatch a command event from JS to Dart. `_convertToDart` is having trouble converting that event to Dart? I'm not sure there's enough info here to diagnose the issue, but I'm happy to step anybody through getting this set up in devtools.

**Comment by jmesserly** [comment]
Just from the stack trace, it looks like a few bugs here:

(1) _convertToDart is getting compiled in such a way that we end up with dcalls. That seems bad. Ideally we should be statically typed in our own runtime libs.

(2) somehow we're showing a null receiver in the nSM. I'm not sure how that can happen given the code:
```js
  function _isBrowserType(o) {
    return o instanceof Blob || o instanceof Event || window.KeyRange && o instanceof KeyRange || o instanceof ImageData || o instanceof Node || window.TypedData && o instanceof TypedData || o instanceof Window;
  }
  // ...
  function _convertToDart(o, isBrowserType) {
    if (isBrowserType === void 0) isBrowserType = null;
    if (isBrowserType == null) isBrowserType = _isBrowserType;
    // isBrowserType is null on next line. How?!
    if (o == null || typeof o == "string" || typeof o == "number" || typeof o == "boolean" || dart.notNull(dart.dcall(isBrowserType, o))) {
```
... looking through checkAndCall, it looks like we are including a bogus receiver in the nSM exception (the bug is in "dcall", which passes null for "obj"). Hard to know exactly where we went awry. I would *guess* checkApply but not 100% sure.

> I'm not sure there's enough info here to diagnose the issue, but I'm happy to step anybody through getting this set up in devtools.

If you can try it, set a breakpoint in `checkAndCall` and see where it goes. Probably into `checkApply`. From there, probably `instanceOfOrNull`. I wonder what we get back from `let actual = rtti.realRuntimeType(obj);` ... whatever we get, I would expect the `types.isSubtype(actual, type)` returns true, since `type` should be dynamic.

One easy fix is to avoid `dcall` there, but regardless we should fix these helpers so they work correctly with any type of object they get passed.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1609843002/ fixes (1) above.

**Comment by devoncarew** [comment]
Thanks for the fix! I'll do some digging on my end w/ devtools.

**Comment by vsmenon** [comment]
There is also this comment in `checkAndCall`:

```
    // TODO(leafp): throw a type error (rather than NSM)
    // if the arity matches but the types are wrong.
```

The NSM might be hiding a runtime type error.  We may not be handling `JSObject<CustomEvent>` (the passed in Object), correctly.

@devoncarew do you know the type of the function getting passing in here?

**Comment by jmesserly** [comment]
I think the function was the one deleted here: https://github.com/dart-lang/dev_compiler/commit/01e0e51a14820c71c97109b87b8f20cc2f752d17
(judging by the stack trace)

signature was (dynamic)->bool

I'm not sure what the argument type was, or why we weren't allowing anything to be passed as `dynamic`

**Comment by devoncarew** [comment]
To update, I recompiled w/ the latest in master and no longer see this issue - I can receive command events in Atom (they show up as the `CustomEvent` type).

**Comment by jmesserly** [comment]
\o/ going to close this out. If there's a bug in dcall helpers (and indeed there's some TODO's there still), we can flush it out when we look through language tests and such.
