### ISSUE TITLE
passing generic function literals

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/dev_compiler#426]
I have the following

```dart
typedef BuiltListProperty<T> BuiltListPropertyFactory<T>(
    Stream<ListMutation<T>> mutations);

BuiltListProperty<Object /*=T*/ > _defaultBuiltListPropertyFactory /*<T>*/ (
        Stream<ListMutation /*<T>*/ > mutations) =>
    new BuiltListProperty<Object /*=T*/ >(mutations);

class BuiltListProperty<E> {
  BuiltListProperty /*<R>*/ map /*<R>*/ (/*=R*/ f(E element),
          [BuiltListPropertyFactory /*<R>*/ builtListFactory =
              _defaultBuiltListPropertyFactory /*<R>*/]) => ...
}
```

The analyzer complains with 
> ERROR: Type check failed: _defaultBuiltListPropertyFactory (<T>(Stream<ListMutation<T>>) → BuiltListProperty<T>) is not of type (Stream<ListMutation<R>>) → BuiltListProperty<R> ([frentity] lib/src/list_property/built_list_property.dart:64)

**Comment by jmesserly** [comment]
Nice example! A few things could be going on here:
* we don't have instantiated tear-off support, so `_defaultBuiltListPropertyFactory /*<R>*/` doesn't parse the `<R>`
* we're not doing downward inference for instantiated tear-offs. Otherwise we'd push the `<R>` down to _defaultBuiltListPropertyFactory.

The error I'm seeing makes a little more sense:
```
[error] Type check failed: _defaultBuiltListPropertyFactory (<T>(dynamic) → BuiltListProperty<T>) is not of type (dynamic) → BuiltListProperty<R>
```

Basically it ends up with the uninstantiated generic function type. So the error message itself is correct, but, it's no good that you can't express what you're trying to express here. I'll see if I can find the bug about instantiated tear-offs & if not, open a new one.

**Comment by jmesserly** [comment]
The other bug is https://github.com/dart-lang/sdk/issues/25175. We thought perhaps we could wait to implement instantiated tear-offs, but this example is a good one for why that doesn't work. :)

It's ugly, but a workaround in the short term might be:
```dart
typedef BuiltListProperty<T> BuiltListPropertyFactory<T>(
    Stream<ListMutation<T>> mutations);

class BuiltListProperty<E> {
  BuiltListProperty /*<R>*/ map /*<R>*/ (/*=R*/ f(E element),
          [BuiltListPropertyFactory /*<R>*/ builtListFactory]) {
    if (builtListFactory == null) {
      builtListFactory = (Stream<ListMutation /*<R>*/ > mutations) =>
          new BuiltListProperty<Object /*=R*/ >(mutations);
    }
  }
}
```

**Comment by jmesserly** [comment]
believe this should be fixed now. Strong mode will infer it.
