### ISSUE TITLE
Static type of "(x) => null" is computed as "(dynamic) => <bottom>"

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#47]
This should be (dynamic) => dynamic per spec as I understand it.  Not sure if this is the analyzer or our mods to it.

@leafpetersen @bwilkerson @sigmundch

**Comment by jmesserly** [comment]
@vsmenon does this still reproduce?

**Comment by vsmenon** [comment]
Yes, here's a repro:

```dart
void foo() {
  var f = (x) => null;
  f = (x) => "hello";
}
```

generates:

```
warning: [UninferredClosure] (x) => "hello" ((dynamic) → String) will need runtime check to cast to type (dynamic) → <bottom>
```

**Comment by jmesserly** [comment]
It looks like this is our inference. In some cases, like local var inference, we're careful not to accept bottom type. However this logic doesn't kick in consistently.

I'm guessing lambda expression return type and return statements have this problem. Upwards generic methods I think is okay, as we reject "bottom" (which can happen sometimes naturally as a result of computing the lower/upper bounds).

**Comment by jmesserly** [comment]
BTW, bottom comes into play as the type of `null`, per the spec.

**Comment by jmesserly** [comment]
haven't figured this out entirely, but my guess is that the static type () -> ⊥ for `() => null` comes from the spec type system. Probably our inference on function expressions should fix that up, in strong mode. Given that we have downward inference, I don't think we'll need to preserve that type as ⊥ (one possibility is to fix this for `null` itself, since the literal itself can be typed as anything from its context, not sure the spec type system treatment gets us anything.)

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1649523002/
