### ISSUE TITLE
dynamic calls on some operators seems broken?

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#502]
The following Dart:

```dart
bool inRange(min, value, max) => (min <= value) && (value <= max);

void main() {
  var result = inRange(2, 7, 10);
  print(result);
}
```

generates this:

```js
  test.inRange = function(min, value, max) {
    return dart.as(dart.dsend(min, '<=', value), core.bool)['&&'](dart.as(dart.dsend(value, '<=', max), core.bool));
  };

  test.main = function() {
    let result = setteronly.inRange(2, 7, 10);
    core.print(result);
  };
```

which, at runtime, triggers:

```
Uncaught TypeError: dart.as(...).&& is not a function
```

It's fine if `inRange` parameters are typed.

**Comment by rakudrama** [comment]
The problem appears to be that the static type on parenthesized expressions is not updated by inserting reified coercions.
We can either make reify_coercions.dart adjust the static type on parentheses (or look through parentheses when querying the type - I prefer adjusting the tree to be correct).

We should also make boolean conversions explicit rather than relying on

      if (dart.notNull(dart.as(x, core.bool))) ...

**Comment by jmesserly** [comment]
> I prefer adjusting the tree to be correct

+1! :)

**Comment by rakudrama** [comment]
Fixed by https://github.com/dart-lang/dev_compiler/commit/961542eb96cd865dcf7eb1d8cca05022fb9fe283
Boolean conversion issue moved to https://github.com/dart-lang/dev_compiler/issues/536
