### ISSUE TITLE
Nested cascade bug

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#516]
```dart
class Foo {
  int x;
}

class Bar {
  Foo foo;
  int y;
}

main() {
  var bars = [ new Bar()
    ..foo = (new Foo()..x = 42)
    ..y = 38 ];
  var bar = bars[0];
  print(bar.foo is Foo);
}
```

prints `false` in DDC.

The generated code looks screwy:
```js
  hello.Foo = class Foo extends core.Object {
    Foo() {
      this.x = null;
    }
  };
  hello.Bar = class Bar extends core.Object {
    Bar() {
      this.foo = null;
      this.y = null;
    }
  };
  hello.main = function() {
    let bars = dart.list([(() => {
        let _ = new hello.Bar();
        _.foo = (() => {
          _.x = 42;
          return _;
        })();
        _.y = 38;
        return _;
      })()], hello.Bar);
    let bar = bars[dartx.get](0);
    core.print(dart.notNull(bar.foo.x) + dart.notNull(bar.y));
  };
```

It appears that `foo` is assigned a `Bar`.

**Comment by vsmenon** [comment]
It prints `true` on the VM.

**Comment by jmesserly** [comment]
Something dropped the "new Foo". That's why it's going so far off the rails :)

**Comment by vsmenon** [comment]
And this slightly modified version prints true.

```dart
main() {
  var bars = <Bar>[ new Bar()
    ..foo = (new Foo()..x = 42)
    ..y = 38 ];
  var bar = bars[0];
  print(bar.foo is Bar);
}
```

**Comment by jmesserly** [comment]
The inner lambda should be:
```js
        (() => {
          let _ = new hello.Foo();
          _.x = 42;
          return _;
        })();
```

**Comment by jmesserly** [comment]
We generate these as essentially `let*` (in the Scheme sense) ... and then "lower" them to JS code. Maybe the lowering of the outer one somehow messes with the inner one, although that shouldn't be happening, naturally. Or maybe we built the wrong `let*` structure from the start. Interesting bug though :)

**Comment by vsmenon** [comment]
Actually, didn't need the list.  Here's a slightly simpler version with the bug:

```dart
main() {
  var bar = new Bar()
    ..foo = (new Foo()..x = 42)
    ..y = 38;
  print(bar.foo is Bar);
}
```

which produces this:

```js
  hello.main = function() {
    let bar = new hello.Bar();
    bar.foo = (() => {
      bar.x = 42;
      return bar;
    })();
    bar.y = 38;
    core.print(dart.is(bar.foo, hello.Bar));
  };
```

**Comment by jmesserly** [comment]
Nice repros. I'm making good progress on tracking this down. MetaLet seems to be confused about how often the temporary variables are used (it must be not counting some uses, because it thinks "_" temp only appears once, but it clearly appears at least twice, for both the outer and inner MetaLet).

**Comment by jmesserly** [comment]
Oh dear. So my (ab)use of js_ast template instantiation is the culprit here. We're incorrectly substituting for the cascade "#_" from the outer expression into the inner one, which breaks some invariants later on, but the root cause is the use of named interpolation exprs (where's capture-avoiding substitution when you need it :) ). No idea what I was thinking when this was written. Perhaps I confused js_ast interpolation with DDC's own temporary variables (which are safe). But as is, this is not a safe design for MetaLet.

I tried removing some of the readability optimizations, but they do make the code much better in a lot of cases.

I think this is fixable though. We should implement a different node, that binds by identity and not name, and use it instead of JS.InterpolatedExpression. (Similar to the difference between JS.TemporaryId vs JS.Identifier)

**Comment by jmesserly** [comment]
Fixed this. I'm going to try one further API cleanup that is unlocked now.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1910233002/
