### ISSUE TITLE
Function types are not fully canonicalized

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/dev_compiler#540]
The function type
```js
dart.functionType(intl._DateFormatField, [dart.dynamic, dart.dynamic])
```
is not canonicalized, leading to the following expression creating a fresh class for each call.
Manually hacking the code to cache the function type speeds up the Intl.DateFormat.format.oneshot benchmark by 5x-8x.

```js
static get _fieldConstructors() {
  return dart.list([
      dart.fn((pattern, parent) => new intl._DateFormatQuotedField(pattern, parent), intl._DateFormatQuotedField, [dart.dynamic, dart.dynamic]),
      dart.fn((pattern, parent) => new intl._DateFormatPatternField(pattern, parent), intl._DateFormatPatternField, [dart.dynamic, dart.dynamic]),
      dart.fn((pattern, parent) => new intl._DateFormatLiteralField(pattern, parent), intl._DateFormatLiteralField, [dart.dynamic, dart.dynamic])],
    dart.functionType(intl._DateFormatField, [dart.dynamic, dart.dynamic]));
}
```

The code comes from `intl/lib/src/intl/date_format.dart
`
```dart
  static List get _fieldConstructors => [
    (pattern, parent) => new _DateFormatQuotedField(pattern, parent),
    (pattern, parent) => new _DateFormatPatternField(pattern, parent),
    (pattern, parent) => new _DateFormatLiteralField(pattern, parent)
  ];
```

**Comment by leafpetersen** [comment]
I've had it in my head to look into canonicalization for runtime types in a uniform way.  It may give us good speedups in the cast code if we can usually count on a fast identity check to succeed.  If we can make types actually canonical so that if identity fails we know they are not equal that might be even better, though for casts and is checks we're checking subtyping so not-equal doesn't allow us to cut off early, unfortunately.

**Comment by rakudrama** [comment]
Without complete canonicalization, the subtype cache will grow without bound. The Intl benchmark grows the cache to >70k elements with all but the first ~20 being the 'same' function.

Something we can probably do quickly is to hoist the expression that creates the type as high as possible, and have an lazy initialized accessor in that scope that creates the type on first use.
This works for unparameterized types too, even if we just hoist to the class.

We will still need fast canonicalization, especially for types derived from type parameters to methods.

```js
(E) => {
  class Foo extends ... {  // Foo<E>
    ...
    core.List$(E).new()
    ...
    core.List$(E).new()
```

becomes something like the following (I'm sure we can make it more pretty).

```js
(E) => {
  let _core_List$_E;  // a 'local' cache
  core_List$_E() =>  _core_List$_E || (_core_List$_E = core.List$(E));

  class Foo extends ... {  // Foo<E>
    ...
    core_List$_E().new()
    ...
    core_List$_E().new()
```

**Comment by leafpetersen** [comment]
I think the dart.generic helper does canonicalize (or at least I thought it used to)?

The dart.functionType etc helpers could do likewise in the short term.

We may want to rethink the subtype cache.  It's not clear to me that caching function types is a win, unless the cache can be keyed only by identity, since I don't think checking general equality of function types is noticeably faster than just checking subtyping.

**Comment by jmesserly** [comment]
> unless the cache can be keyed only by identity

IIRC, it is only keyed by identity.
https://github.com/dart-lang/dev_compiler/blob/4d27e3f409afaec75a9501eccbe4e52c5ace999f/tool/input_sdk/private/ddc_runtime/types.dart#L425

**Comment by vsmenon** [comment]
@leafpetersen can we close this?  I think you fixed.

**Comment by leafpetersen** [comment]
Done.
