### ISSUE TITLE
Call methods on classes not supported

### ISSUE THREAD

**Issue by vsmenon** [dart-lang/dev_compiler#542]
The following code breaks:

```dart
typedef int Int2Int(int x);

class Foo {
  int y;
  Foo(this.y);

  int call(int x) => x + y;
}

void main() {
  var foo = new Foo(42);
  print(foo(38));

  Int2Int f = new Foo(42);
  print(f(38));
}
```

Both the call to `foo` and `f` (if the former is commented out) throw in JS.

**Comment by munificent** [comment]
I'll take this if it's up for grabs.

**Comment by munificent** [comment]
Never mind!

**Comment by jmesserly** [comment]
https://github.com/dart-lang/dev_compiler/issues/542 - codegen for them. Still need to fix runtime subtyping though, from the looks of it.

**Comment by jmesserly** [comment]
Oh so the test failures are not for the reason I thought -- we seem perhaps(?) overly aggressive on our strong mode is check failures. (we don't allow `void call(bool a, {int b}) {}` to be checked against `typedef void Baz(bool a, {String b});` ... since it's a sideways cast, and we agree with Dart's type system on that, not sure why we throw from `is`?)

However there is still a problem in the CL, I'll add a comment to it.

**Comment by jmesserly** [comment]
So one big issue here: because the class *instances* are now functions, we have to be careful in how we assign some instance fields, such as "name" (e.g. and others such as arguments/caller/callee).

We also may end up shadowing some methods on Function.prototype, such as "bind" "apply" and "call". That is fine conceptually, but it may break assumptions in our hand coded "dart." runtime functions (and in JS libraries that these functions get passed to). One way around that is to always symbolize those Dart member names.

Overall I'm not sure how I feel about the CL. It's worrying me a bit that we will have a long tail of quirks in any class that happens to have a "call" method/getter/field.

I wonder if it would be worth exploring an alternate approach, where we consider the coercion from interface type to function type to not preserve identity, e.g.
```dart
class C {
  int call(int x) => x + 1;
}
typedef int Int2Int(int x);
main() {
  C c = new C();
  Int2Int f = c;
  print(identical(c, f));
}
```

It would be totally possible to make dynamic operations treat "c" and "f" identically, and to make them "==" eachother, but that would allow a different representation between the two types when the static type is used.

**Comment by jmesserly** [comment]
Going to say this is fixed enough, bug for remaining issues is:
https://github.com/dart-lang/dev_compiler/issues/593

Note, contrary to my commit comment, subtype checks are working.
