### ISSUE TITLE
When toString is called on a JavaScript symbol from Dart an exception is thrown

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dev_compiler#577]
The issue is that dart toString ends up calling
```javascript
"" + Symbol("foo") 
```
which throws an exception while
```javascript
Symbol("foo").toString()
```
is fine.
I believe this behavior changed in a recent version of chrome likely to match the ES6 spec.

**Comment by rakudrama** [comment]
1. Can we install an extension method on Symbol and use that to convert symbols however we want?

2. We could change `"" + x` back to  `x.toString()` and special-case String and num arguments before the extension method lookup.  That is probably fastest for a lot of real-world code.

**Comment by jmesserly** [comment]
> I believe this behavior changed in a recent version of chrome likely to match the ES6 spec.

It was caused by a regression in DDC: https://codereview.chromium.org/1989663002/diff/1/tool/input_sdk/private/ddc_runtime/operations.dart#newcode469

additive operators evaluation is described [here](http://www.ecma-international.org/ecma-262/6.0/#sec-addition-operator-plus-runtime-semantics-evaluation), which uses [ToString](http://www.ecma-international.org/ecma-262/6.0/#sec-tostring) which throws a TypeError for ES Symbol. 

Short term, I think we should go back to toString.

Making a JSSymbol `@Native` type for EcmaScript Symbols is a good idea. That would likely improve a lot of things about how they are handled in DDC. But that might have other implications, so I'd rather scope that into its own bug.

**Comment by jmesserly** [comment]
https://github.com/dart-lang/dev_compiler/issues/578 for that really nice `@Native` JS Symbol idea.

**Comment by jmesserly** [comment]
https://codereview.chromium.org/1993293002/
