### ISSUE TITLE
Missing return in _emitModule

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dev_compiler#583]
`_emitModule` ([lib/src/compiler/code_generator.dart](https://github.com/dart-lang/dev_compiler/blob/master/lib/src/compiler/code_generator.dart#L202)) ends with a switch over an enum, but there is no default case, or return statement after the switch (for when the enum's value is null).

**Comment by jmesserly** [comment]
@srawlins -- how do I structure this in a good way? Switch over enums has to be exhaustive. The lack of a default case is intentional: if someone adds a new ModuleFormat, we want a warning that a case is missing. That is very important. If I add a "default" case, we'll lose the warning too. It won't let me add "case null" because it says "null cannot be a ModuleFormat". Either way I would be adding dead code, because options.moduleFormat is not really nullable.

**Comment by jmesserly** [comment]
IMO, it would be better to ignore the null case, since in practice one does not typically switch over null (without it already being a bug of some sort). In other words, suppress the hint when one already has an exhaustive switch over enums.

**Comment by jmesserly** [comment]
This was fixed.
