### ISSUE TITLE
html apis that take optional parameters don't work anymore

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dev_compiler#628]
running sunflower I see this error:
```
TypeError: Failed to execute 'stroke' on 'CanvasRenderingContext2D': parameter 1 is not of type 'Path2D'.(…)
```
it's coming from this method:
```dart
  /// Draw a small circle representing a seed centered at (x,y).
  void draw(CanvasRenderingContext2D context) {
    context
      ..beginPath()
      ..lineWidth = 2
      ..fillStyle = color
      ..strokeStyle = color
      ..arc(x, y, radius, 0, TAU, false)
      ..fill()
      ..closePath()
      ..stroke();
  }
```
The code that implements "stroke" is:
```js
    [dartx.stroke](path) {
      return this.stroke(path);
    }
```
The runtime value there is "undefined"

**Comment by jmesserly** [comment]
@jacob314 seen anything like this before?

**Comment by vsmenon** [comment]
The nicest solution would be to handle this caller side.  I.e., anything calling a DOM API that simply forwards just calls the forwarded API instead.

E.g., generate `context.stroke()` instead of `context[dartx.stroke]()`.

This wouldn't work for overridable methods (e.g., CustomElements) though.  The old solution in dart2js / dartium was something like:

```
    [dartx.stroke](path) {
      if (path == void 0) {
        return this.stroke();
      } else {
        return this.stroke(path);
      }
    }
```

**Comment by vsmenon** [comment]
This issue was moved to dart-lang/sdk#27429
